name: CI

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Configure TestContainers cloud
      uses: atomicjar/testcontainers-cloud-setup-action@main
      with:
        wait: true
        token: ${{ secrets.TC_CLOUD_TOKEN }}

    - name: Build and Test
      run: |
        bazel build //...
        bazel test --test_output=all //...
